name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test Python script
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m unittest discover -s . -p '*_test.py'

    - name: Build Docker image
      run: docker build -t surveillance-app .

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker image
      run: |
        docker tag surveillance-app ${{ secrets.DOCKER_USERNAME }}/surveillance-app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/surveillance-app:latest